server:
  port: 8088
spring:
  application:
    name: knowledge-service
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://192.168.10.146:5432/postgres
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:knowledge-service.yaml