server:
  port: 8084
spring:
  application:
    name: preview-service
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://192.168.10.146:5432/postgres
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      config:
        file-extension: yaml
        server-addr: 192.168.10.146:8848
      discovery:
        server-addr: 192.168.10.146:8848
  config:
    import:
      - optional:nacos:preview-service.yaml